version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /opt/frontend/node_modules
      - ./src:/opt/frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/frontend/node_modules
      - ./src:/opt/frontend/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]