version: '3'
services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    depends_on:
      - postgres
    build:
      dockerfile: ./Dockerfile.dev
      context: ./api
    volumes:
      - /opt/api/node_modules
      - ./api:/opt/api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432

  client:
    build:
      dockerfile: ./Dockerfile.dev
      context: ./client
    volumes:
      - /opt/client/node_modules
      - ./client:/opt/client

  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: ./Dockerfile.dev
      context: ./worker
    volumes:
      - /opt/worker/node_modules
      - ./worker:/opt/worker