apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: client
spec:
  containers:
    - name: client
      image: isometria/dkw-10-client
      ports:
        - containerPort: 3000